.PHONY: default install-opencv 

.DEFAULT_GOAL := default


default: build

build: 
	go build



# it uses the openCV Makefile to install openCV in the system easily
install-opencv:
	make -f Makefile.opencv install


